In [63]:
import numpy as np
import pandas as pd
import seaborn as sns
import torch

In [64]:
df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [65]:
df = df.drop_duplicates()
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [66]:
df = df.drop(columns=["embarked", "class", "alive"])
df

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,man,True,NaN,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,woman,False,NaN,Queenstown,False
887,1,1,female,19.0,0,0,30.0000,woman,False,B,Southampton,True
888,0,3,female,NaN,1,2,23.4500,woman,False,NaN,Southampton,False
889,1,1,male,26.0,0,0,30.0000,man,True,C,Cherbourg,True
890,0,3,male,32.0,0,0,7.7500,man,True,NaN,Queenstown,True

In [67]:
df['age'] = df['age'].fillna(df.groupby(['pclass', 'sex'])['age'].transform('median'))
df

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,man,True,NaN,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,woman,False,NaN,Queenstown,False
887,1,1,female,19.0,0,0,30.0000,woman,False,B,Southampton,True
888,0,3,female,22.0,1,2,23.4500,woman,False,NaN,Southampton,False
889,1,1,male,26.0,0,0,30.0000,man,True,C,Cherbourg,True
890,0,3,male,32.0,0,0,7.7500,man,True,NaN,Queenstown,True

In [68]:
df[df['embark_town'].isna()]

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
61,1,1,female,38.0,0,0,80.0,woman,False,B,NaN,True
829,1,1,female,62.0,0,0,80.0,woman,False,B,NaN,True

In [69]:
df = df.drop([61, 829], axis=0)

In [70]:
df = df.reset_index(drop=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,man,True,NaN,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...
777,0,3,female,39.0,0,5,29.1250,woman,False,NaN,Queenstown,False
778,1,1,female,19.0,0,0,30.0000,woman,False,B,Southampton,True
779,0,3,female,22.0,1,2,23.4500,woman,False,NaN,Southampton,False
780,1,1,male,26.0,0,0,30.0000,man,True,C,Cherbourg,True
781,0,3,male,32.0,0,0,7.7500,man,True,NaN,Queenstown,True

In [71]:
df['deck'] = df['deck'].cat.add_categories('Unknown')
df['deck'] = df['deck'].fillna('Unknown')
df

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,man,True,Unknown,Southampton,False
1,1,1,female,38.0,1,0,71.2833,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,woman,False,Unknown,Southampton,True
3,1,1,female,35.0,1,0,53.1000,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,man,True,Unknown,Southampton,True
...,...,...,...,...,...,...,...,...,...,...,...,...
777,0,3,female,39.0,0,5,29.1250,woman,False,Unknown,Queenstown,False
778,1,1,female,19.0,0,0,30.0000,woman,False,B,Southampton,True
779,0,3,female,22.0,1,2,23.4500,woman,False,Unknown,Southampton,False
780,1,1,male,26.0,0,0,30.0000,man,True,C,Cherbourg,True
781,0,3,male,32.0,0,0,7.7500,man,True,Unknown,Queenstown,True

In [72]:
df.groupby("embark_town")["survived"].agg(["mean", "count"])

                 mean  count
embark_town
Cherbourg    0.580645    155
Queenstown   0.338983     59
Southampton  0.371479    568

In [73]:
df = pd.get_dummies(df, columns=["sex", "who", "deck", "embark_town"], drop_first=True, dtype=np.int64)
df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,who_man,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_Unknown,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,True,False,1,1,0,0,0,0,0,0,0,1,0,1
1,1,1,38.0,1,0,71.2833,False,False,0,0,1,0,1,0,0,0,0,0,0,0
2,1,3,26.0,0,0,7.9250,False,True,0,0,1,0,0,0,0,0,0,1,0,1
3,1,1,35.0,1,0,53.1000,False,False,0,0,1,0,1,0,0,0,0,0,0,1
4,0,3,35.0,0,0,8.0500,True,True,1,1,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,0,3,39.0,0,5,29.1250,False,False,0,0,1,0,0,0,0,0,0,1,1,0
778,1,1,19.0,0,0,30.0000,False,True,0,0,1,1,0,0,0,0,0,0,0,1
779,0,3,22.0,1,2,23.4500,False,False,0,0,1,0,0,0,0,0,0,1,0,1
780,1,1,26.0,0,0,30.0000,True,True,1,1,0,0,1,0,0,0,0,0,0,0
781,0,3,32.0,0,0,7.7500,True,True,1,1,0,0,0,0,0,0,0,1,1,0

In [74]:
df["adult_male"] = df["adult_male"].astype(np.int64)
df["alone"] = df["alone"].astype(np.int64)
df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,who_man,who_woman,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_Unknown,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,1,0,1,1,0,0,0,0,0,0,0,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0,0,1,0,1,0,0,0,0,0,0,0
2,1,3,26.0,0,0,7.9250,0,1,0,0,1,0,0,0,0,0,0,1,0,1
3,1,1,35.0,1,0,53.1000,0,0,0,0,1,0,1,0,0,0,0,0,0,1
4,0,3,35.0,0,0,8.0500,1,1,1,1,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,0,3,39.0,0,5,29.1250,0,0,0,0,1,0,0,0,0,0,0,1,1,0
778,1,1,19.0,0,0,30.0000,0,1,0,0,1,1,0,0,0,0,0,0,0,1
779,0,3,22.0,1,2,23.4500,0,0,0,0,1,0,0,0,0,0,0,1,0,1
780,1,1,26.0,0,0,30.0000,1,1,1,1,0,0,1,0,0,0,0,0,0,0
781,0,3,32.0,0,0,7.7500,1,1,1,1,0,0,0,0,0,0,0,1,1,0

In [75]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   survived                 782 non-null    int64
 1   pclass                   782 non-null    int64
 2   age                      782 non-null    float64
 3   sibsp                    782 non-null    int64
 4   parch                    782 non-null    int64
 5   fare                     782 non-null    float64
 6   adult_male               782 non-null    int64
 7   alone                    782 non-null    int64
 8   sex_male                 782 non-null    int64
 9   who_man                  782 non-null    int64
 10  who_woman                782 non-null    int64
 11  deck_B                   782 non-null    int64
 12  deck_C                   782 non-null    int64
 13  deck_D                   782 non-null    int64
 14  deck_E                   782 non-null    int64
 15  deck_F                   782 non-null    int64
 16  deck_G                   782 non-null    int64
 17  deck_Unknown             782 non-null    int64
 18  embark_town_Queenstown   782 non-null    int64
 19  embark_town_Southampton  782 non-null    int64
dtypes: float64(2), int64(18)
memory usage: 122.3 KB

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop('survived', axis=1).values
y = df['survived'].values
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_temp)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

In [77]:
from torch.utils.data import TensorDataset, DataLoader


X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)

X_val_t = torch.tensor(X_val, dtype=torch.float32)
y_val_t = torch.tensor(y_val, dtype=torch.float32).unsqueeze(1)

X_test_t = torch.tensor(X_test, dtype=torch.float32)
y_test_t = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

train_dataset = TensorDataset(X_train_t, y_train_t)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [78]:
from torch import nn, no_grad


class TitanicMLP(nn.Module):
    def __init__(self, n_features, hidden_size=16):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_features, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, 1)
        )

    def forward(self, x):
        return self.net(x)

In [79]:
input_dim = X_train_t.shape[1]
model = TitanicMLP(n_features=input_dim, hidden_size=16)
loss_fn = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [80]:
train_losses = []
val_losses = []

epochs = 90

for epoch in range(epochs):

    model.train()
    total_loss = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        logits = model(X_batch)
        loss = loss_fn(logits, y_batch)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * len(X_batch)

    train_loss = total_loss / len(train_dataset)
    model.eval()

    with torch.no_grad():
        val_logits = model(X_val_t)
        val_loss = loss_fn(val_logits, y_val_t).item()

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    if (epoch + 1) % 10 == 0:
        print(
            f"Epoch {epoch + 1}: train={train_loss:.4f}, val={val_loss:.4f}"
        )

Epoch 10: train=0.5632, val=0.4916
Epoch 20: train=0.5136, val=0.4734
Epoch 30: train=0.4936, val=0.4610
Epoch 40: train=0.4801, val=0.4493
Epoch 50: train=0.4729, val=0.4427
Epoch 60: train=0.4659, val=0.4386
Epoch 70: train=0.4603, val=0.4372
Epoch 80: train=0.4602, val=0.4335
Epoch 90: train=0.4591, val=0.4322

In [81]:
with torch.no_grad():
    logits = model(X_test_t)
    probabilities = torch.sigmoid(logits)
    predictions = (probabilities >= 0.5).int()

In [82]:
from sklearn.metrics import roc_auc_score, classification_report

boosting_roc_auc = roc_auc_score(y_test_t, probabilities)
print(classification_report(y_test_t, predictions))
print(f"ROC-AUC {boosting_roc_auc}")

              precision    recall  f1-score   support

         0.0       0.75      0.89      0.82        47
         1.0       0.78      0.56      0.65        32

    accuracy                           0.76        79
   macro avg       0.77      0.73      0.74        79
weighted avg       0.76      0.76      0.75        79

ROC-AUC 0.8507313829787234